use crate::driver::traits::Driver;
use crate::generators::naming::{column_to_field_name, escape_reserved, table_to_type_name};
use crate::plugin::plugin::{Catalog, Schema, Table};
use crate::utils::CodeWriter;

/// Generate the models.gleam file from the catalog.
pub fn generate_models(catalog: &Catalog, driver: &dyn Driver) -> String {
    let mut w = CodeWriter::new();
    w.line("// Code generated by sqlc-gen-gleam. DO NOT EDIT.");
    w.blank();

    let mut needs_option_import = false;

    // Collect all tables and check if any have nullable columns
    let tables: Vec<&Table> = catalog
        .schemas
        .iter()
        .flat_map(|s| &s.tables)
        .collect();

    for table in &tables {
        for col in &table.columns {
            if !col.not_null {
                needs_option_import = true;
            }
        }
    }

    if needs_option_import {
        w.line("import gleam/option.{type Option}");
        w.blank();
    }

    // Generate enums from all schemas
    for schema in &catalog.schemas {
        for enum_def in &schema.enums {
            generate_enum(enum_def, schema, w.borrow_mut());
            w.blank();
        }
    }

    // Generate type for each table
    let mut first = true;
    for table in &tables {
        if !first {
            w.blank();
        }
        first = false;
        generate_table_type(table, &mut w, driver);
    }

    w.into_string()
}

fn generate_table_type(table: &Table, w: &mut CodeWriter, driver: &dyn Driver) {
    let table_name = table
        .rel
        .as_ref()
        .map(|r| r.name.as_str())
        .unwrap_or("unknown");
    let type_name = table_to_type_name(table_name);

    if !table.comment.is_empty() {
        w.writef(format_args!("/// {}", table.comment));
    }

    w.writef(format_args!("pub type {type_name} {{"));
    w.indent();

    let fields: Vec<String> = table
        .columns
        .iter()
        .map(|col| {
            let field_name = escape_reserved(&column_to_field_name(&col.name));
            let resolved = driver.resolve_column_type(col);
            format!("{field_name}: {}", resolved.type_expr)
        })
        .collect();

    w.writef(format_args!("{type_name}({})", fields.join(", ")));
    w.dedent();
    w.line("}");
}

fn generate_enum(enum_def: &crate::plugin::plugin::Enum, schema: &Schema, w: &mut CodeWriter) {
    let prefix = if schema.name != "public" && !schema.name.is_empty() {
        format!("{}_{}", schema.name, enum_def.name)
    } else {
        enum_def.name.clone()
    };
    let type_name = crate::generators::naming::to_pascal_case(&prefix);

    if !enum_def.comment.is_empty() {
        w.writef(format_args!("/// {}", enum_def.comment));
    }
    w.writef(format_args!("pub type {type_name} {{"));
    w.indent();
    for val in &enum_def.vals {
        let variant = crate::generators::naming::to_pascal_case(val);
        w.line(&variant);
    }
    w.dedent();
    w.line("}");

    // Generate to_string / from_string helpers
    w.blank();
    w.writef(format_args!(
        "pub fn {}_to_string(val: {type_name}) -> String {{",
        crate::generators::naming::to_snake_case(&type_name)
    ));
    w.indent();
    w.line("case val {");
    w.indent();
    for val in &enum_def.vals {
        let variant = crate::generators::naming::to_pascal_case(val);
        w.writef(format_args!("{variant} -> \"{val}\""));
    }
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");

    w.blank();
    w.writef(format_args!(
        "pub fn {}_from_string(s: String) -> Result({type_name}, Nil) {{",
        crate::generators::naming::to_snake_case(&type_name)
    ));
    w.indent();
    w.line("case s {");
    w.indent();
    for val in &enum_def.vals {
        let variant = crate::generators::naming::to_pascal_case(val);
        w.writef(format_args!("\"{val}\" -> Ok({variant})"));
    }
    w.line("_ -> Error(Nil)");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");
}

impl CodeWriter {
    fn borrow_mut(&mut self) -> &mut CodeWriter {
        self
    }
}
