use crate::codegen::TableMap;
use crate::driver::query_gen::generate_query_fn;
use crate::driver::traits::Driver;
use crate::options::TypeOverride;
use crate::plugin::plugin::Query;
use crate::utils::CodeWriter;

/// Generate a Gleam query module for a group of queries from the same SQL file.
pub fn generate_queries(queries: &[&Query], _module_name: &str, table_map: &TableMap, overrides: &[TypeOverride], driver: &dyn Driver) -> String {
    let mut w = CodeWriter::new();
    w.line("// Code generated by sqlc-gen-gleam. DO NOT EDIT.");
    w.blank();

    // Collect import flags
    let mut needs_option = false;
    let mut needs_execrows = false;
    let mut needs_array = false;
    let mut needs_copyfrom = false;
    let mut needs_slice = false;

    for query in queries {
        for col in &query.columns {
            if !col.not_null {
                needs_option = true;
            }
        }
        for param in &query.params {
            if let Some(col) = &param.column {
                if !col.not_null {
                    needs_option = true;
                }
                if col.is_array {
                    needs_array = true;
                }
                if col.is_sqlc_slice {
                    needs_slice = true;
                }
            }
        }
        if query.cmd == ":execrows" {
            needs_execrows = true;
        }
        if query.cmd == ":copyfrom" {
            needs_copyfrom = true;
        }
    }

    driver.write_imports(needs_option, needs_execrows, needs_array, needs_copyfrom, needs_slice, &mut w);
    w.blank();

    // Emit helper for :execrows tag parsing (PostgreSQL only)
    if needs_execrows {
        driver.write_execrows_helper(&mut w);
        if driver.execrows_needs_tag_parse() {
            w.blank();
        }
    }

    let mut first = true;
    for query in queries {
        if !first {
            w.blank();
        }
        first = false;
        generate_query_fn(query, table_map, overrides, &mut w, driver);
    }

    w.into_string()
}
