use crate::codegen::TableMap;
use crate::driver::query_gen::{build_insert_param_map, generate_query_fn};
use crate::driver::traits::Driver;
use crate::options::TypeOverride;
use crate::plugin::plugin::{Column, Query};
use crate::utils::CodeWriter;

/// Check if a column is nullable in its source table definition.
/// Used to detect when sqlc loses nullability through type casts.
/// Falls back to searching all tables by column name when table ref is missing.
fn is_nullable_in_source(col: &Column, table_map: &TableMap) -> bool {
    let col_name = if !col.original_name.is_empty() {
        &col.original_name
    } else {
        &col.name
    };

    if col_name.is_empty() {
        return false;
    }

    // Try table reference first
    if let Some(ref table_ref) = col.table {
        if !table_ref.name.is_empty() {
            let table = table_map.get(&table_ref.name).or_else(|| {
                if !table_ref.schema.is_empty() {
                    table_map.get(&format!("{}.{}", table_ref.schema, table_ref.name))
                } else {
                    None
                }
            });
            if let Some(table) = table {
                if let Some(orig_col) = table.columns.iter().find(|c| c.name == *col_name) {
                    return !orig_col.not_null;
                }
            }
            return false;
        }
    }

    // Fallback: search all tables
    for table in table_map.values() {
        if let Some(orig_col) = table.columns.iter().find(|c| c.name == *col_name) {
            if !orig_col.not_null {
                return true;
            }
        }
    }
    false
}

/// Check if a parameter has a nullable target in an INSERT query.
/// Used when sqlc strips column name/table from cast params (e.g., `$5::uuid`).
fn is_insert_param_nullable(param: &crate::plugin::plugin::Parameter, query: &Query, table_map: &TableMap) -> bool {
    let col = match &param.column {
        Some(c) => c,
        None => return false,
    };
    // Only applies when the column name is missing (cast params)
    if !col.name.is_empty() || !col.original_name.is_empty() {
        return false;
    }
    let insert_map = build_insert_param_map(&query.text, &query.insert_into_table);
    if let Some(col_name) = insert_map.get(&param.number) {
        if let Some(ref table_id) = query.insert_into_table {
            let table = table_map.get(&table_id.name);
            if let Some(table) = table {
                if let Some(orig_col) = table.columns.iter().find(|c| c.name == *col_name) {
                    return !orig_col.not_null;
                }
            }
        }
    }
    false
}

/// Generate a Gleam query module for a group of queries from the same SQL file.
pub fn generate_queries(queries: &[&Query], _module_name: &str, table_map: &TableMap, overrides: &[TypeOverride], driver: &dyn Driver) -> String {
    let mut w = CodeWriter::new();
    w.line("// Code generated by sqlc-gen-gleam. DO NOT EDIT.");
    w.blank();

    // Collect import flags
    let mut needs_option = false;
    let mut needs_execrows = false;
    let mut needs_array = false;
    let mut needs_copyfrom = false;
    let mut needs_slice = false;

    for query in queries {
        for col in &query.columns {
            // Check both sqlc's not_null and the original column's nullability
            // (sqlc may lose nullability through type casts like `col::text`)
            let is_nullable = !col.not_null || is_nullable_in_source(col, table_map);
            if is_nullable {
                needs_option = true;
            }
        }
        for param in &query.params {
            if let Some(col) = &param.column {
                // Check both sqlc's not_null and the source table column's nullability.
                // sqlc may mark param columns as not_null even when the target column
                // is nullable (e.g., `$5::uuid` for a nullable UUID column).
                // Also check INSERT param mapping for cast params with stripped names.
                if !col.not_null || is_nullable_in_source(col, table_map)
                    || is_insert_param_nullable(param, query, table_map) {
                    needs_option = true;
                }
                if col.is_array {
                    needs_array = true;
                }
                if col.is_sqlc_slice {
                    needs_slice = true;
                }
            }
        }
        if query.cmd == ":execrows" {
            needs_execrows = true;
        }
        if query.cmd == ":copyfrom" {
            needs_copyfrom = true;
        }
    }

    driver.write_imports(needs_option, needs_execrows, needs_array, needs_copyfrom, needs_slice, &mut w);
    w.blank();

    // Emit helper for :execrows tag parsing (PostgreSQL only)
    if needs_execrows {
        driver.write_execrows_helper(&mut w);
        if driver.execrows_needs_tag_parse() {
            w.blank();
        }
    }

    let mut first = true;
    for query in queries {
        if !first {
            w.blank();
        }
        first = false;
        generate_query_fn(query, table_map, overrides, &mut w, driver);
    }

    w.into_string()
}
