version: "2"
plugins:
  - name: gleam
    wasm:
      url: file://../../target/wasm32-wasip1/release/sqlc-gen-gleam.wasm
      sha256: eba88e83ea0a101572cf94769f1a66310b65f5aa3472ffc1392374f6bcbf348b
sql:
  - schema: "postgresql/authors/schema.sql"
    queries: "postgresql/authors/query.sql"
    engine: "postgresql"
    codegen:
      - plugin: gleam
        out: "postgresql/authors/generated"
  - schema: "postgresql/types/schema.sql"
    queries: "postgresql/types/query.sql"
    engine: "postgresql"
    codegen:
      - plugin: gleam
        out: "postgresql/types/generated"
