name = "sqlc_sqlite_e2e_test"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glite = ">= 0.1.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
